Fix Deploy Scripts

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -68,6 +68,7 @@ jobs:
           TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
           TF_VAR_region: ${{ vars.GCP_REGION }}
           TF_VAR_tags: ${{ env.instance_name}}
+          TF_VAR_GCS_BACKEND_BUCKET: ${{ vars.GCS_BACKEND_BUCKET }}
         run: terraform plan -out=tfplan
         working-directory: deployment/terraform
 
@@ -87,5 +88,44 @@ jobs:
           TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
           TF_VAR_region: ${{ vars.GCP_REGION }}
           TF_VAR_tags: ${{ env.instance_name}}
+          TF_VAR_GCS_BACKEND_BUCKET: ${{ vars.GCS_BACKEND_BUCKET }}
         run: terraform apply -auto-approve tfplan
         working-directory: deployment/terraform
+
+
+      - name: Wait for SSH to be Ready
+        run: |
+          for i in {1..20}; do
+            if gcloud compute ssh ${{ env.instance_name }} --zone=${{ vars.GCP_ZONE }} --command="echo SSH is ready" &>/dev/null; then
+              echo "SSH is ready."
+              exit 0
+            fi
+            echo "Waiting for SSH to be ready..."
+            sleep 15
+          done
+          echo "SSH did not become ready in time."
+          exit 1
+
+      - name: Set Log Path
+        run: echo "STARTUP_LOG=/var/log/startup_script.log" >> $GITHUB_ENV
+
+      - name: Stream Startup Script Log
+        if: always()
+        run: |
+          gcloud compute ssh ${{ env.instance_name }} --zone=${{ vars.GCP_ZONE }} --command="
+            LOG_FILE='${{ env.STARTUP_LOG }}'
+            while ! grep 'Startup script execution completed' \$LOG_FILE &>/dev/null; do
+              sudo tail -n 20 \$LOG_FILE || echo 'Log not found yet'
+              sleep 30
+            done
+            sudo tail -n 20 \$LOG_FILE
+          "
+
+      - name: Clean up OS Login SSH Keys
+        if: always()
+        run: |
+          # List all SSH keys for the current account
+          KEYS=$(gcloud compute os-login ssh-keys list --format="value(key)")
+          for KEY in $KEYS; do
+            gcloud compute os-login ssh-keys remove --key="$KEY" || true
+          done
