fix docker compose command

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -72,7 +72,7 @@ jobs:
               cp \".env.\$ENVIRONMENT\" .env || { echo \"Failed to copy .env file.\" >> \"\$LOG_FILE\"; exit 1; }
               echo \"Restarting Docker Compose...\" >> \"\$LOG_FILE\"
               docker-compose down >> \"\$LOG_FILE\" 2>&1
-              docker-compose up -d >> \"\$LOG_FILE\" 2>&1 || { echo \"Failed to restart Docker Compose.\" >> \"\$LOG_FILE\"; exit 1; }
+              docker-compose -f docker-compose.yml up -d >> \"\$LOG_FILE\" 2>&1 || { echo \"Failed to restart Docker Compose.\" >> \"\$LOG_FILE\"; exit 1; }
               echo \"Update script execution completed at \$(date)\" >> \"\$LOG_FILE\"
             '"
 
