Update backup

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -12,29 +12,60 @@ on:
           - demo
           - staging
           - prod
-      zone:
-        description: "GCP zone where the instance is located"
-        required: true
-        default: "us-central1-a"
 
 jobs:
   update-repo:
     name: Update Repository and Restart Docker
     runs-on: ubuntu-latest
+    if: github.event_name == 'workflow_dispatch'
 
     steps:
-      # Authenticate with Google Cloud using service account key
-      - name: Authenticate to Google Cloud
+      steps:
+      - name: Validate Environment
+        id: validate-env
         run: |
-          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > ${{ github.workspace }}/key.json
-          gcloud auth activate-service-account --key-file=${{ github.workspace }}/key.json
-          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
+          if [[ "${{ github.event.inputs.environment }}" =~ ^(demo|staging|prod)$ ]]; then
+            echo "environment=${{ github.event.inputs.environment || 'demo' }}" >> $GITHUB_ENV
+          else
+            echo "Invalid environment: ${{ github.event.inputs.environment }}"
+            exit 1
+          fi
+
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Authenticate to Google Cloud
+        uses: google-github-actions/auth@v2
+        with:
+          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
+          export_environment_variables: true
+
+      - name: Set up Google Cloud SDK
+        uses: google-github-actions/setup-gcloud@v2
+        with:
+          install_components: 'beta'
+
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: 1.11.4
+    
+      - name: Terraform Init with Backend
+        run: terraform init -backend-config="bucket=${{ secrets.GCS_BACKEND_BUCKET }}" -backend-config="prefix=tfstate/${{ env.environment }}" -lock=true
+        working-directory: deployment/terraform
+        # Fetch Zone from Terraform Outputs
+      - name: Fetch Zone
+        id: fetch-zone
+        run: |
+          echo "instance_zone=$(terraform output -raw instance_zone)" >> $GITHUB_ENV
+          echo "instance_name=$(terraform output -raw instance_name)" >> $GITHUB_ENV
+        working-directory: deployment/terraform
 
       # Create and run update.sh in a single command as deploy user
       - name: Create and Run update.sh on Instance as Deploy User
         run: |
-          gcloud compute ssh homegeek${{ github.event.inputs.environment }} \
-            --zone=${{ github.event.inputs.zone }} \
+          gcloud compute ssh ${{env.instance_name}} \
+            --zone=${{env.instance_zone}} \
             --command "sudo -u deploy bash -c '
               set -e
               LOG_FILE=\"/home/deploy/update.log\"
@@ -63,16 +94,9 @@ jobs:
       - name: Retrieve Update Log
         if: always()
         run: |
-          gcloud compute ssh homegeek${{ github.event.inputs.environment }} \
-            --zone=${{ github.event.inputs.zone }} \
+          gcloud compute ssh ${{env.instance_name}} \
+            --zone=${{env.instance_zone}} \
             --command "bash -c '
               set -e
               sudo -u deploy bash -c \"cat /home/deploy/update.log\"
             '" || echo "Failed to retrieve log file"
-
-      # Clean up sensitive data (Cleanup)
-      - name: Clean Up
-        if: always()
-        run: |
-          rm -f ${{ github.workspace }}/key.json
-          echo "Temporary service account key file removed."
