Fix scripts

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -32,40 +32,43 @@ jobs:
       # Update repository and restart Docker Compose
       - name: Update Repository and Restart Docker
         run: |
-          gcloud compute ssh 'homegeek${{secrets.GCP_PROJECT_ID }} \
+          gcloud compute ssh homegeek@${{ secrets.GCP_PROJECT_ID }} \
             --zone=${{ github.event.inputs.zone }} \
-            --command "
+            --command "bash -c '
               set -e
-              LOG_FILE='/home/deploy/update.log'
-              echo 'Update script execution started at \$(date)' >> \$LOG_FILE
+              LOG_FILE=\"/home/deploy/update.log\"
+              echo \"Update script execution started at \$(date)\" >> \$LOG_FILE
 
               # Switch to deploy user
-              sudo -u deploy bash <<'EOF'
-              set -e
+              sudo -u deploy bash -c \"
+                set -e
 
-              # Pull the latest changes from the repository
-              echo 'Pulling latest changes from repository...' >> \$LOG_FILE
-              cd /home/deploy/HomeAMA
-              rm .env
-              git pull origin main >> \$LOG_FILE 2>&1
-              if [ \$? -eq 0 ]; then
-                echo 'Repository updated successfully.' >> \$LOG_FILE
-              else
-                echo 'Failed to update repository.' >> \$LOG_FILE
-                exit 1
-              fi
-              cp .env.$${{ github.event.inputs.environment }} .env
-              # Restart Docker Compose
-              echo 'Restarting Docker Compose...' >> \$LOG_FILE
-              docker-compose down >> \$LOG_FILE 2>&1
-              docker-compose up -d >> \$LOG_FILE 2>&1
-              if [ \$? -eq 0 ]; then
-                echo 'Docker Compose restarted successfully.' >> \$LOG_FILE
-              else
-                echo 'Failed to restart Docker Compose.' >> \$LOG_FILE
-                exit 1
-              fi
+                # Pull the latest changes from the repository
+                echo 'Pulling latest changes from repository...' >> \$LOG_FILE
+                cd /home/deploy/HomeAMA
+                rm -f .env
+                git pull origin main >> \$LOG_FILE 2>&1
+                if [ \$? -eq 0 ]; then
+                  echo 'Repository updated successfully.' >> \$LOG_FILE
+                else
+                  echo 'Failed to update repository.' >> \$LOG_FILE
+                  exit 1
+                fi
 
-              echo 'Update script execution completed at \$(date)' >> \$LOG_FILE
-              EOF
-            "
+                # Copy environment file
+                cp .env.${{ github.event.inputs.environment }} .env
+
+                # Restart Docker Compose
+                echo 'Restarting Docker Compose...' >> \$LOG_FILE
+                docker-compose down >> \$LOG_FILE 2>&1
+                docker-compose up -d >> \$LOG_FILE 2>&1
+                if [ \$? -eq 0 ]; then
+                  echo 'Docker Compose restarted successfully.' >> \$LOG_FILE
+                else
+                  echo 'Failed to restart Docker Compose.' >> \$LOG_FILE
+                  exit 1
+                fi
+
+                echo 'Update script execution completed at \$(date)' >> \$LOG_FILE
+              \"
+            '"
